# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12zYFliVSamGLN3VDIlceKRRdH9CFJVyV

# Proyek Akhir: Menyelesaikan Permasalahan Perusahaan Edutech

- Nama: Felix Winston
- Email: felixlim140@gmail.com
- Id Dicoding: felixwlimz

## Persiapan

### Menyiapkan library yang dibutuhkan
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install tensorflow

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from joblib import load
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

"""### Menyiapkan data yang akan diguankan

## Data Understanding
"""

# Baca file dari CSV
df = pd.read_csv('data.csv', sep=';')
df

# Describe shape
df.shape

"""Data Tersebut berjumlah 4424 baris dan 37 kolom"""

# Check for unique values
df.nunique()

# Check for missing values
df.isnull().sum()

"""Data tersebut tidak ada data yang kosong"""

# Check for duplicates
df.duplicated().sum()

"""Data tersebut tidak duplikat"""

# Describe data
df.describe()

df.info()

"""## EDA - Univariate"""

# Plot by Martial Status
sns.set(style="whitegrid")
plt.pie(df['Marital_status'].value_counts(),
        labels=df['Marital_status'].unique(),
        autopct='%1.1f%%',
        startangle=140,
        colors=sns.color_palette("pastel"))
plt.title('Distribution of Marital Status')
plt.tight_layout()
plt.show()

"""Dari distribusi status pernikahan di atas, mayoritas mahasiswa belum menikah, yaitu sekitar 88.6%"""

# Count by attendance in daytime or evening
plt.pie(df['Daytime_evening_attendance'].value_counts(), labels=df['Daytime_evening_attendance'].value_counts().index, autopct='%1.1f%%', startangle=140)
plt.title('Distribution of Attendance')
plt.show()

"""Berdasarkan jumlah kehadiran, 89.1% mahasiswa berkuliah di sore hari, sedangkan sekitar 10.9% berkuliah di pagi hari"""

# Count by displacement

plt.pie(df['Displaced'].value_counts(), labels=df['Displaced'].value_counts().index, autopct='%1.1f%%', startangle=140)
plt.title('Distribution of Displacement')
plt.show()

"""Berdasarkan grafik diatas, 54.8% mahasiswa merupakan mahasiswa pindahan"""

# Count by Debtor
plt.pie(df['Debtor'].value_counts(), labels=df['Debtor'].unique(), autopct='%1.1f%%', startangle=140)
plt.title('Distribution of Debtor')
plt.show()

"""Dari data diatas, 11.4% mahasiswa merupakan peminjam"""

# Dropout status by gender

plt.pie(x=df['Gender'].value_counts(), labels=df['Gender'].value_counts().index, autopct='%1.1f%%', startangle=90)
plt.title('Dropout status by Gender')
plt.show()

# Dropout status by International student
plt.pie(x=df['International'].value_counts(), labels=df['International'].value_counts().index, autopct='%1.1f%%', startangle=90)
plt.title('Dropout status by International student')
plt.show()

# Educational Special needs
plt.pie(x=df['Educational_special_needs'].value_counts(), labels=df['Educational_special_needs'].value_counts().index, autopct='%1.1f%%', startangle=90)
plt.title('Dropout status by Educational special needs')
plt.show()

"""Data diatas menunjukkan bahwa 1.2% mahasiswa yang dropout merupakan penerima bantuan khusus perkuliahan"""

# Tution fees up to date

plt.pie(x=df['Tuition_fees_up_to_date'].value_counts(), labels=df['Tuition_fees_up_to_date'].value_counts().index, autopct='%1.1f%%', startangle=90)
plt.title('Tuition fees up to date')
plt.show()

# Student Status ( Target )
plt.pie(x=df['Status'].value_counts(), labels=df['Status'].value_counts().index, autopct='%1.1f%%', startangle=90)
plt.title('Dropout status')
plt.show()

# Distribution of age at enrollment

plt.figure(figsize=(10, 6))
sns.histplot(df['Age_at_enrollment'], bins=20, kde=True)
plt.title('Distribution of Age at Enrollment')
plt.xlabel('Age at Enrollment')
plt.ylabel('Frequency')
plt.show()

# Admission grade
plt.figure(figsize=(10, 6))
sns.histplot(df['Admission_grade'], bins=20, kde=True)
plt.title('Admission Grade')
plt.xlabel('Admission Grade')
plt.ylabel('Frequency')
plt.show()

# Previous qualification
plt.figure(figsize=(10, 6))
sns.histplot(df['Previous_qualification_grade'], bins=20, kde=True)
plt.title('Previous Qualification')
plt.xlabel('Previous Qualification')
plt.ylabel('Frequency')
plt.xticks(rotation=45)
plt.show()

"""## EDA - Multivariate"""

# Checking correlation between features
plt.figure(figsize=(20, 20))

df_copy = df.drop(columns='Status')

sns.heatmap(df_copy.corr(), annot=True, fmt=".2f", cmap='coolwarm', square=True)
plt.title('Correlation Matrix')
plt.show()

"""## Data Preparation / Preprocessing"""

# Check for missing values
df.isnull().sum()

# Check for duplicate values
df.duplicated().sum()

df.info()

# Convert categorical variables to numerical
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
label_encoder = LabelEncoder()

df['Status'] = label_encoder.fit_transform(df['Status'])

# Normalize the data
scaler = StandardScaler()
scaler.fit_transform(df)

# Split the data into features and target variable
X = df.drop(columns=['Status'])
y = df['Status']

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""## Modeling"""

# Use Logistic Regression as baseline model
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)

# Evaluate the model
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
plt.title('Confusion Matrix')
plt.show()

# Using Other Models - Random Forest
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

# Evaluate the Random Forest model
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))
# Confusion Matrix for Random Forest
cm_rf = confusion_matrix(y_test, y_pred_rf)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
plt.title('Confusion Matrix - Random Forest')

# Commented out IPython magic to ensure Python compatibility.
# %pip install xgboost

# Using Other Models - XGBoost
from sklearn.svm import SVC
svc = SVC(kernel='linear', random_state=42)
svc.fit(X_train, y_train)
y_pred_svc = svc.predict(X_test)

# Evaluate the SVC model
print("SVC Accuracy:", accuracy_score(y_test, y_pred_svc))
print("Classification Report:\n", classification_report(y_test, y_pred_svc))
# Confusion Matrix for SVC
cm_svc = confusion_matrix(y_test, y_pred_svc)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_svc, annot=True, fmt='d', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
plt.title('Confusion Matrix - SVC')

# Use Deep Learning Model

model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    BatchNormalization(),
    Dropout(0.3),
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(3, activation='softmax')   # Assuming binary classification for dropout status
])

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])


model.summary()

# Train the model
history = model.fit(X_train, y_train, epochs=100, batch_size=64, validation_split=0.2)
# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}")
# Plot training history
plt.figure(figsize=(12, 6))
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""## Evaluation"""

# Use pd Dataframe for checking the accuracy of the models
from sklearn.metrics import f1_score

results = pd.DataFrame({
    'Model': ['Logistic Regression', 'Random Forest', 'SVC', 'Deep Learning'],
    'Accuracy': [accuracy_score(y_test, y_pred), accuracy_score(y_test, y_pred_rf), accuracy_score(y_test, y_pred_svc), accuracy],
    'F1 Score': [f1_score(y_test, y_pred, average='weighted'), f1_score(y_test, y_pred_rf, average='weighted'), f1_score(y_test, y_pred_svc, average='weighted'), f1_score(y_test, model.predict(X_test).argmax(axis=1), average='weighted')],
})
results = results.sort_values(by='Accuracy', ascending=False)
results